version: '3.4'
services:
  vapor:
    build: .
    command: --env=production --hostname=0.0.0.0
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    external_links:
      - db:db
      - redis:redis
    environment:
      DB_PASSWORD_FILE: "/database-service-password"
      DB_HOST: "db"
      DB_PORT: 5432
      DB_USERNAME: "user"
      DB_DATABASE: "user"
      REDIS_URL: "redis://redis"
    volumes:
      - ./tmp/database-service-password:/database-service-password

  db:
    image: postgis/postgis
    environment:
      POSTGRES_USER: "user"
      POSTGRES_DBNAME: "user"
      POSTGRES_PASSWORD_FILE: "/database-service-password"
      PGDATA: "/var/lib/postgresql/data/db-files/"
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./tmp/data
        target: /var/lib/postgresql/data
      - ./tmp/database-service-password:/database-service-password
      - ./reverse-geodecoding-data.sql:/docker-entrypoint-initdb.d/reverse-geodecoding-data.sql
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
