version: 2

jobs:
  linux:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test

  linux-release:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run:
          name: Compile code with optimizations
          command: swift build -c release


  bionic-swift-5-1:
    docker:
      - image: vapor/swift:5.1-bionic
    steps:
      - checkout
      - run: apt-get -qq update && apt-get -q -y install libpq-dev libssl-dev zlib1g-dev postgresql postgresql-client postgresql-contrib
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test

  bionic-swift-5-1-release:
    docker:
      - image: vapor/swift:5.1-bionic
    steps:
      - checkout
      - run: apt-get -qq update && apt-get -q -y install libpq-dev libssl-dev zlib1g-dev postgresql postgresql-client postgresql-contrib
      - run:
          name: Compile code with optimizations
          command: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-release
      - bionic-swift-5-1
      - bionic-swift-5-1-release
