version: 2

jobs:
  linux:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test

  linux-release:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run:
          name: Compile code with optimizations
          command: swift build -c release


  linux-swift-5:
    docker:
      - image: swift:5.0
    steps:
      - checkout
      - run: apt-get -qq update && apt-get -q -y install libpq-dev libssl-dev zlib1g-dev postgresql postgresql-client postgresql-contrib
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test

  linux-swift-5-release:
    docker:
      - image: swift:5.0
    steps:
      - checkout
      - run: apt-get -qq update && apt-get -q -y install libpq-dev libssl-dev zlib1g-dev postgresql postgresql-client postgresql-contrib
      - run:
          name: Compile code with optimizations
          command: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-release
      - linux-swift-5
      - linux-swift-5-release
